<?php

declare(strict_types=1);

namespace Modules\Flight\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Flight\Models\Airport;

class AirportSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $airports = [
            // Asia
            [
                'iata_code' => 'HND',
                'name' => 'Haneda Airport',
                'city' => 'Tokyo',
                'country' => 'Japan',
                'timezone' => 'Asia/Tokyo',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'NRT',
                'name' => 'Narita International Airport',
                'city' => 'Tokyo',
                'country' => 'Japan',
                'timezone' => 'Asia/Tokyo',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'DEL',
                'name' => 'Indira Gandhi International Airport',
                'city' => 'Delhi',
                'country' => 'India',
                'timezone' => 'Asia/Kolkata',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'BOM',
                'name' => 'Chhatrapati Shivaji International Airport',
                'city' => 'Mumbai',
                'country' => 'India',
                'timezone' => 'Asia/Kolkata',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'MAA',
                'name' => 'Chennai International Airport',
                'city' => 'Chennai',
                'country' => 'India',
                'timezone' => 'Asia/Kolkata',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'BLR',
                'name' => 'Kempegowda International Airport',
                'city' => 'Bangalore',
                'country' => 'India',
                'timezone' => 'Asia/Kolkata',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'HYD',
                'name' => 'Rajiv Gandhi International Airport',
                'city' => 'Hyderabad',
                'country' => 'India',
                'timezone' => 'Asia/Kolkata',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'CCU',
                'name' => 'Netaji Subhas Chandra Bose International Airport',
                'city' => 'Kolkata',
                'country' => 'India',
                'timezone' => 'Asia/Kolkata',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'SIN',
                'name' => 'Singapore Changi Airport',
                'city' => 'Singapore',
                'country' => 'Singapore',
                'timezone' => 'Asia/Singapore',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'ICN',
                'name' => 'Incheon International Airport',
                'city' => 'Seoul',
                'country' => 'South Korea',
                'timezone' => 'Asia/Seoul',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'HKG',
                'name' => 'Hong Kong International Airport',
                'city' => 'Hong Kong',
                'country' => 'China',
                'timezone' => 'Asia/Hong_Kong',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'BKK',
                'name' => 'Suvarnabhumi Airport',
                'city' => 'Bangkok',
                'country' => 'Thailand',
                'timezone' => 'Asia/Bangkok',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'KUL',
                'name' => 'Kuala Lumpur International Airport',
                'city' => 'Kuala Lumpur',
                'country' => 'Malaysia',
                'timezone' => 'Asia/Kuala_Lumpur',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'CGK',
                'name' => 'Soekarno-Hatta International Airport',
                'city' => 'Jakarta',
                'country' => 'Indonesia',
                'timezone' => 'Asia/Jakarta',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'MNL',
                'name' => 'Ninoy Aquino International Airport',
                'city' => 'Manila',
                'country' => 'Philippines',
                'timezone' => 'Asia/Manila',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Europe
            [
                'iata_code' => 'LHR',
                'name' => 'London Heathrow Airport',
                'city' => 'London',
                'country' => 'United Kingdom',
                'timezone' => 'Europe/London',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'CDG',
                'name' => 'Charles de Gaulle Airport',
                'city' => 'Paris',
                'country' => 'France',
                'timezone' => 'Europe/Paris',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'FRA',
                'name' => 'Frankfurt Airport',
                'city' => 'Frankfurt',
                'country' => 'Germany',
                'timezone' => 'Europe/Berlin',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'AMS',
                'name' => 'Amsterdam Airport Schiphol',
                'city' => 'Amsterdam',
                'country' => 'Netherlands',
                'timezone' => 'Europe/Amsterdam',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'MAD',
                'name' => 'Adolfo Suárez Madrid–Barajas Airport',
                'city' => 'Madrid',
                'country' => 'Spain',
                'timezone' => 'Europe/Madrid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'FCO',
                'name' => 'Leonardo da Vinci International Airport',
                'city' => 'Rome',
                'country' => 'Italy',
                'timezone' => 'Europe/Rome',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'IST',
                'name' => 'Istanbul Airport',
                'city' => 'Istanbul',
                'country' => 'Turkey',
                'timezone' => 'Europe/Istanbul',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'DME',
                'name' => 'Moscow Domodedovo Airport',
                'city' => 'Moscow',
                'country' => 'Russia',
                'timezone' => 'Europe/Moscow',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'ZRH',
                'name' => 'Zurich Airport',
                'city' => 'Zurich',
                'country' => 'Switzerland',
                'timezone' => 'Europe/Zurich',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'CPH',
                'name' => 'Copenhagen Airport',
                'city' => 'Copenhagen',
                'country' => 'Denmark',
                'timezone' => 'Europe/Copenhagen',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'ARN',
                'name' => 'Stockholm Arlanda Airport',
                'city' => 'Stockholm',
                'country' => 'Sweden',
                'timezone' => 'Europe/Stockholm',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // North America
            [
                'iata_code' => 'JFK',
                'name' => 'John F. Kennedy International Airport',
                'city' => 'New York',
                'country' => 'United States',
                'timezone' => 'America/New_York',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'LAX',
                'name' => 'Los Angeles International Airport',
                'city' => 'Los Angeles',
                'country' => 'United States',
                'timezone' => 'America/Los_Angeles',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'ORD',
                'name' => "O'Hare International Airport",
                'city' => 'Chicago',
                'country' => 'United States',
                'timezone' => 'America/Chicago',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'MIA',
                'name' => 'Miami International Airport',
                'city' => 'Miami',
                'country' => 'United States',
                'timezone' => 'America/New_York',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'SFO',
                'name' => 'San Francisco International Airport',
                'city' => 'San Francisco',
                'country' => 'United States',
                'timezone' => 'America/Los_Angeles',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'DFW',
                'name' => 'Dallas/Fort Worth International Airport',
                'city' => 'Dallas',
                'country' => 'United States',
                'timezone' => 'America/Chicago',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'YYZ',
                'name' => 'Toronto Pearson International Airport',
                'city' => 'Toronto',
                'country' => 'Canada',
                'timezone' => 'America/Toronto',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'YVR',
                'name' => 'Vancouver International Airport',
                'city' => 'Vancouver',
                'country' => 'Canada',
                'timezone' => 'America/Vancouver',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'YUL',
                'name' => 'Montréal-Pierre Elliott Trudeau International Airport',
                'city' => 'Montreal',
                'country' => 'Canada',
                'timezone' => 'America/Montreal',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'MEX',
                'name' => 'Benito Juárez International Airport',
                'city' => 'Mexico City',
                'country' => 'Mexico',
                'timezone' => 'America/Mexico_City',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // South America
            [
                'iata_code' => 'GRU',
                'name' => 'São Paulo/Guarulhos International Airport',
                'city' => 'São Paulo',
                'country' => 'Brazil',
                'timezone' => 'America/Sao_Paulo',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'EZE',
                'name' => 'Ministro Pistarini International Airport',
                'city' => 'Buenos Aires',
                'country' => 'Argentina',
                'timezone' => 'America/Argentina/Buenos_Aires',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'BOG',
                'name' => 'El Dorado International Airport',
                'city' => 'Bogotá',
                'country' => 'Colombia',
                'timezone' => 'America/Bogota',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'SCL',
                'name' => 'Arturo Merino Benítez International Airport',
                'city' => 'Santiago',
                'country' => 'Chile',
                'timezone' => 'America/Santiago',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'LIM',
                'name' => 'Jorge Chávez International Airport',
                'city' => 'Lima',
                'country' => 'Peru',
                'timezone' => 'America/Lima',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Middle East
            [
                'iata_code' => 'DXB',
                'name' => 'Dubai International Airport',
                'city' => 'Dubai',
                'country' => 'United Arab Emirates',
                'timezone' => 'Asia/Dubai',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'AUH',
                'name' => 'Abu Dhabi International Airport',
                'city' => 'Abu Dhabi',
                'country' => 'United Arab Emirates',
                'timezone' => 'Asia/Dubai',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'DOH',
                'name' => 'Hamad International Airport',
                'city' => 'Doha',
                'country' => 'Qatar',
                'timezone' => 'Asia/Qatar',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'RUH',
                'name' => 'King Khalid International Airport',
                'city' => 'Riyadh',
                'country' => 'Saudi Arabia',
                'timezone' => 'Asia/Riyadh',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'JED',
                'name' => 'King Abdulaziz International Airport',
                'city' => 'Jeddah',
                'country' => 'Saudi Arabia',
                'timezone' => 'Asia/Riyadh',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Africa
            [
                'iata_code' => 'JNB',
                'name' => 'O.R. Tambo International Airport',
                'city' => 'Johannesburg',
                'country' => 'South Africa',
                'timezone' => 'Africa/Johannesburg',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'CPT',
                'name' => 'Cape Town International Airport',
                'city' => 'Cape Town',
                'country' => 'South Africa',
                'timezone' => 'Africa/Johannesburg',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'CAI',
                'name' => 'Cairo International Airport',
                'city' => 'Cairo',
                'country' => 'Egypt',
                'timezone' => 'Africa/Cairo',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'ADD',
                'name' => 'Bole International Airport',
                'city' => 'Addis Ababa',
                'country' => 'Ethiopia',
                'timezone' => 'Africa/Addis_Ababa',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'NBO',
                'name' => 'Jomo Kenyatta International Airport',
                'city' => 'Nairobi',
                'country' => 'Kenya',
                'timezone' => 'Africa/Nairobi',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Oceania
            [
                'iata_code' => 'SYD',
                'name' => 'Sydney Airport',
                'city' => 'Sydney',
                'country' => 'Australia',
                'timezone' => 'Australia/Sydney',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'MEL',
                'name' => 'Melbourne Airport',
                'city' => 'Melbourne',
                'country' => 'Australia',
                'timezone' => 'Australia/Melbourne',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'BNE',
                'name' => 'Brisbane Airport',
                'city' => 'Brisbane',
                'country' => 'Australia',
                'timezone' => 'Australia/Brisbane',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'PER',
                'name' => 'Perth Airport',
                'city' => 'Perth',
                'country' => 'Australia',
                'timezone' => 'Australia/Perth',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'AKL',
                'name' => 'Auckland Airport',
                'city' => 'Auckland',
                'country' => 'New Zealand',
                'timezone' => 'Pacific/Auckland',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'iata_code' => 'CHC',
                'name' => 'Christchurch International Airport',
                'city' => 'Christchurch',
                'country' => 'New Zealand',
                'timezone' => 'Pacific/Auckland',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        Airport::insert($airports);
    }
}
